### PR TITLE
Ensure $log_server is an array for easy iteration in template

### PR DESCRIPTION
**Pull request by Phil-Friderici**

### CODE REVIEW

**Comment by sharlander** [comment]
@Phil-Friderici i guess we should do it like Garrett mentioned 

i got this in mind:

<pre>
<% if @log_server.class == Array -%>
<% @log_server.each do |server| -%>
<%= @source_facilities %> <% if @transport_protocol == 'tcp' -%>@<% end -%>@<%= server -%>:<%= @log_server_port %>
<% end -%>
<% else -%>
<%= @source_facilities %> <% if @transport_protocol == 'tcp' -%>@<% end -%>@<%= @log_server -%>:<%= @log_server_port %>
<% end -%>
</pre>

it's set to a string by default and hiera can only override it with a string or an array so it's ensured that "log_server" is not nil

**Comment by Phil-Friderici** [comment]
@sharlander ja, this would be the way @ghoneycutt described it.
Nethertheless, I think that Garrett will also prefer to put the conditional logic into Puppet code.

Of course, both way will work.

I have added spec tests to try this.
Need a hand to activate Travis testing on your repo ?

**Comment by Phil-Friderici** [comment]
See Travis working on that here: https://github.com/Phil-Friderici/puppet-module-rsyslog/pull/2

**Comment by Phil-Friderici** [comment]
btw: my PR doesn't touch the template. You still need to change `for` to `each.` like you did in the example above. No need to support strings in template anymore :)

<pre>
<% @log_server.each do |server| -%>
<%= @source_facilities %> <% if @transport_protocol == 'tcp' -%>@<% end -%>@<%= server -%>:<%= @log_server_port %>
<% end -%>
</pre>

**Comment by sharlander** [comment]
@Phil-Friderici alright thanks, special thanks for the spec tests ;)

**Comment by Phil-Friderici** [comment]
not at all :)

**Pull request merged**
